# Generated by Django 5.2.12 on 2026-08-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_obligationvehicle_temporality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('sport', 'Sport'), ('personal', 'Personal'), ('non_permanent_use', 'Non Permanent Use'), ('permanent_use', 'Permanent Use'), ('water', 'Water'), ('trailer', 'Trailer')], max_length=30),
        ),
    ]
